### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by bessone** [CyberfusionIO/python3-cyberfusion-powerdns-secondary-cleaner#1]
Hello,

first of all thanks for your code, just these days I have to fix some secondaries.

But I have a problem, it gives me a connection timeout error to the primary.
From the same machine the calls work, both the web interface and the API, what can it be?

I also leave the error returned (I removed the real IP)

Thanks for the help

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bessone/.local/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='1.2.3.4', port=80): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bessone/.local/bin/powerdns-secondary-cleaner", line 8, in <module>
    sys.exit(main())
  File "/home/bessone/.local/lib/python3.10/site-packages/powerdns_secondary_cleaner/CLI.py", line 48, in main
    primary_zones = primary_api.get_zones()
  File "/home/bessone/.local/lib/python3.10/site-packages/powerdns_secondary_cleaner/powerdns_api.py", line 51, in get_zones
    zones = self._execute_get_request("zones")
  File "/home/bessone/.local/lib/python3.10/site-packages/powerdns_secondary_cleaner/powerdns_api.py", line 31, in _execute_get_request
    request = requests.get(
  File "/home/bessone/.local/lib/python3.10/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/bessone/.local/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/bessone/.local/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bessone/.local/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/bessone/.local/lib/python3.10/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='1.2.3.4', port=80): Read timed out. (read timeout=10)
```

**Comment by WilliamDEdwards** [comment]
According to the error message, you specified port 80. Is that correct? The PowerDNS API runs on port 8081 by default.

**Comment by bessone** [comment]
I didn't specify it, I also censored my real server port, of course I used the correct one in the code.

**Comment by WilliamDEdwards** [comment]
Regarding censoring: please read https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open.

Regarding your issue: hard to say. The first thing that comes to mind is that you specified an IPv4 address, but confirmed that the primary is reachable with a dual-stack DNS name, and it is reachable only over IPv6. Or the other way around, but I don't know that because of the censoring.
